// <auto-generated />
namespace Jop_Offers_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addnewjop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewjop));
        
        string IMigrationMetadata.Id
        {
            get { return "201902191631266_addnewjop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
